# Dockerfile.api
FROM python:3.9-slim-buster
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ predict_api.py
COPY src/utils.py utils.py
# Add any other necessary files like model artifacts if not using MLflow registry solely
ENV MLFLOW_TRACKING_URI=http://mlflow:5000
ENV MLFLOW_MODEL_NAME=ProjetAIModel
ENV MLFLOW_MODEL_STAGE=Production
EXPOSE 8000
EXPOSE 8001
CMD ["uvicorn", "predict_api:app", "--host", "0.0.0.0", "--port", "8000"]