# Dockerfile.streamlit
FROM python:3.9-slim-buster
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/streamlit_dashboard.py .
ENV FASTAPI_URL=http://api:8000/predict
EXPOSE 8501
CMD ["streamlit", "run", "streamlit_dashboard.py", "--server.port", "8501", "--server.address", "0.0.0.0"]