# prometheus.yml
global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['api:8001'] # Use Docker service name and Prometheus port from FastAPI
   #You could add another job for Streamlit if it also exposes metrics
  - job_name: 'streamlit_app'
    static_configs:
      - targets: ['streamlit:8002']