# grafana/datasources/datasource.yml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090 # Use Docker service name
    isDefault: true
    access: proxy
    editable: true